
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# Explicit imports to satisfy Flake8
#from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import *
import mysql.connector


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Downloads\Sem 5 Data\DBMS\Theory\Dashboard Project\Figma Version\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

conn = mysql.connector.connect(user='root', password='0000', host='localhost', database='python', auth_plugin='mysql_native_password')
cursor = conn.cursor()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

def getqty(id):
    id = str(id)
    command = 'select qty from fruits where id='+id
    cursor.execute(command)
    return cursor.fetchall()

def refresh_labels():
    l=[label_12,label_34, label_56, label_78]
    id=[1,2,3,4]
    for i in range(len(l)):
        canvas.itemconfigure(l[i], text=getqty(id[i]))

def increment(id):
    id = str(id)
    cursor.execute('update fruits set qty=qty+1 where id='+id)
    refresh_labels()

def decrement(id):
    id = str(id)
    cursor.execute('update fruits set qty=qty-1 where id='+id)
    refresh_labels()

canvas.create_rectangle(
    85.0,
    563.0,
    1165.0,
    665.0,
    fill="#FFFFFF",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    230.0,
    614.0,
    image=image_image_2
)

canvas.create_text(
    95.0,
    595.0,
    anchor="nw",
    text="4.",
    fill="#000000",
    font=("NewsreaderRoman Light", 40 * -1)
)

canvas.create_text(
    350.0,
    584.0,
    anchor="nw",
    text="Banana - 1 kg",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: decrement(1),
    relief="flat"
)
button_1.place(
    x=1050.0,
    y=584.0,
    width=60.0,
    height=60.0
)

label_12 = canvas.create_text(
    925.0,
    584.0,
    anchor="nw",
    text="NA12",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: increment(1),
    relief="flat"
)
button_2.place(
    x=825.0,
    y=584.0,
    width=60.0,
    height=60.0
)

canvas.create_rectangle(
    85.0,
    431.0,
    1165.0,
    533.0,
    fill="#FFFFFF",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    230.0,
    485.0,
    image=image_image_3
)

canvas.create_text(
    95.0,
    466.0,
    anchor="nw",
    text="3.",
    fill="#000000",
    font=("NewsreaderRoman Light", 40 * -1)
)

canvas.create_text(
    350.0,
    455.0,
    anchor="nw",
    text="Orange - 1 kg",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: decrement(2),
    relief="flat"
)
button_3.place(
    x=1050.0,
    y=452.0,
    width=60.0,
    height=60.0
)

label_34 = canvas.create_text(
    925.0,
    452.0,
    anchor="nw",
    text="NA34",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: increment(2),
    relief="flat"
)
button_4.place(
    x=825.0,
    y=452.0,
    width=60.0,
    height=60.0
)

canvas.create_rectangle(
    85.0,
    299.0,
    1165.0,
    401.0,
    fill="#FFFFFF",
    #alpha=0.5,
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    230.0,
    346.0,
    image=image_image_4
)

canvas.create_text(
    95.0,
    332.0,
    anchor="nw",
    text="2.",
    fill="#000000",
    font=("NewsreaderRoman Light", 40 * -1)
)

canvas.create_text(
    350.0,
    316.0,
    anchor="nw",
    text="Mango - 1 kg",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: decrement(3),
    relief="flat"
)
button_5.place(
    x=1050.0,
    y=320.0,
    width=60.0,
    height=60.0
)

label_56 = canvas.create_text(
    925.0,
    320.0,
    anchor="nw",
    text="NA56",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: increment(3),
    relief="flat"
)
button_6.place(
    x=825.0,
    y=320.0,
    width=60.0,
    height=60.0
)

canvas.create_rectangle(
    85.0,
    167.0,
    1165.0,
    269.0,
    fill="#FFFFFF",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    230.0,
    217.0,
    image=image_image_5
)

canvas.create_text(
    95.0,
    198.0,
    anchor="nw",
    text="1.",
    fill="#000000",
    font=("NewsreaderRoman Light", 40 * -1)
)

canvas.create_text(
    350.0,
    187.0,
    anchor="nw",
    text="Apple - 1 kg",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: decrement(4),
    relief="flat"
)
button_7.place(
    x=1050.0,
    y=185.0,
    width=60.0,
    height=60.0
)

label_78 = canvas.create_text(
    925.0,
    185.0,
    anchor="nw",
    text="NA78",
    fill="#000000",
    font=("OpenSansRoman Light", 40 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: increment(4),
    relief="flat"
)
button_8.place(
    x=825.0,
    y=185.0,
    width=60.0,
    height=60.0
)

canvas.create_text(
    85.0,
    50.0,
    anchor="nw",
    text="Inventory",
    fill="#000000",
    font=("Product Sans", 64 * -1)
)

save_image = PhotoImage(
    file=relative_to_assets("save.png"))

save = Button(
    image=save_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: cursor.execute('commit'),
    relief="flat"
)

save.place(
    x=550.0,
    y=668.0,
    width=140.0,
    height=55.0
)

refresh_labels()
window.resizable(False, False)
window.mainloop()
